### ISSUE TITLE
Request have return error

### ISSUE THREAD

**Issue by ccycv** [monero-integrations/monerowhmcs#34]
Hello,

    I just want to test this module but looks like is not working for me.. I have configured with multiple remote hosts from this page : https://moneroworld.com/#nodes and non of these are working for me, I did a telnet and works..

RuntimeException: Request have return error: Method not found; 
Request: {"jsonrpc":"2.0","method":"make_integrated_address","params":{"payment_id":"4bb9494c6124abd9"},"id":1}; Check the daemon hostname and daemon port settings in the Monero Pyament Gateway WHMCS config. in /home/lifetimehosting/public_html/my/modules/gateways/monero/library.php:169
Stack trace:
#0 /home/lifetimehosting/public_html/my/modules/gateways/monero/library.php(120): Monero_rpc->validate(true, 'Request have re...')
#1 /home/lifetimehosting/public_html/my/modules/gateways/monero/library.php(231): Monero_rpc->request('make_integrated...', Array)
#2 /home/lifetimehosting/public_html/my/modules/gateways/monero/library.php(292): Monero_rpc->_run('make_integrated...', Array)
#3 /home/lifetimehosting/public_html/my/modules/gateways/monero/createinvoice.php(39): Monero_rpc->make_integrated_address('4bb9494c6124abd...')
#4 {main}

Thanks

**Comment by ccycv** [comment]
I have found the problem, you have to run local a rpc...
